-- MySQL Script generated by MySQL Workbench
-- Mon May 21 14:14:42 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbprojeto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbprojeto` ;

-- -----------------------------------------------------
-- Schema dbprojeto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbprojeto` DEFAULT CHARACTER SET utf8 ;
USE `dbprojeto` ;

-- -----------------------------------------------------
-- Table `dbprojeto`.`tblUsuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbprojeto`.`tblUsuario` ;

CREATE TABLE IF NOT EXISTS `dbprojeto`.`tblUsuario` (
  `idtblUsuario` INT NOT NULL auto_increment,
  `tblUsuarioNome` VARCHAR(70) NOT NULL,
  `tblUsuarioEmail` VARCHAR(70) NOT NULL,
  `tblUsuarioSenha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtblUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbprojeto`.`tblMensagens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbprojeto`.`tblMensagens` ;

CREATE TABLE IF NOT EXISTS `dbprojeto`.`tblMensagens` (
  `idtblMensagens` INT NOT NULL auto_increment,
  `tblMensagensPergunta` VARCHAR(200) NULL,
  `tblMensagenResposta` VARCHAR(200) NOT NULL,
  `tblMensagensPalChave` VARCHAR(40) NOT NULL,
  `tblMensagensData` DATETIME NOT NULL,
  `tblMensagensUsuario` VARCHAR(45) NULL,
  `tblMensagensTentativas` INT NULL,
  
  PRIMARY KEY (`idtblMensagens`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbprojeto`.`tblRelatorioUso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbprojeto`.`tblAtendimento` ;

CREATE TABLE IF NOT EXISTS `dbprojeto`.`tblAtendimento` (
  `idtblUso` INT NOT NULL auto_increment,
  `tblAtdData` TIMESTAMP NOT NULL,
  `tblUsoEncaminhado` INT NULL,
  `tblUsoInteracao` INT NULL,
  `tblUsoTent` VARCHAR(45) NULL ,
  `tblRelatorioIdMensagens` VARCHAR(45) NULL ,
  PRIMARY KEY (`idtblUso`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;